#!/bin/bash

. ../shell/functions

# 实例的端口号。
PORT=$2

# 实例的类型。
ROLE=$3

# 实例的集群名称。
REPLSETNAME=$4

# 脚本所在目录。
# 这里要注意下，如果写 /usr/bin/cd 会有问题。
PATH_SHELL_FOLDER=$(cd `dirname $0`;/usr/bin/pwd)

# 实例文件夹根目录。
PATH_DATA_ROOT=${PATH_SHELL_FOLDER}/${PORT}

# 实例的配置文件。
PATH_CONF=${PATH_DATA_ROOT}/conf/mongodb.${PORT}.conf

# 服务的配置文件。
PATH_SERVICE=/usr/lib/systemd/system/mongod.${PORT}.service

# 实例的配置文件模板。
TEMPLATE_CONF=${PATH_SHELL_FOLDER}/mongod.conf.sample

# 根据实例的类型修改配置文件模板。
if [[ "mongos" == ${ROLE} ]];
then
    TEMPLATE_CONF=${PATH_SHELL_FOLDER}/mongos.conf.sample
elif [[ "single" = ${ROLE} ]]; 
then
    TEMPLATE_CONF=${PATH_SHELL_FOLDER}/mongod.conf.single
fi

# 服务的配置文件模板。
TEMPLATE_SERVICE=${PATH_SHELL_FOLDER}/mongod.service.sample

# 根据实例的类型修改配置文件模板。
if [[ "mongos" == ${ROLE} ]];
then
    TEMPLATE_SERVICE=${PATH_SHELL_FOLDER}/mongos.service.sample
fi

install_service() {
if [ ! -d ${PATH_DATA_ROOT} ];
then
    echo_green "创建实例文件夹："
    ${SHELL_MKDIR} -p ${PATH_DATA_ROOT}/conf
    ${SHELL_MKDIR} -p ${PATH_DATA_ROOT}/data
    ${SHELL_MKDIR} -p ${PATH_DATA_ROOT}/logs
    ${SHELL_MKDIR} -p ${PATH_DATA_ROOT}/tmp

    echo_green "创建实例配置文件："
    ${SHELL_CP} ${TEMPLATE_CONF} ${PATH_CONF}
    ${SHELL_SED} -i "s/\${PORT}/${PORT}/g" ${PATH_CONF}
    ${SHELL_SED} -i "s/\${REPLSETNAME}/${REPLSETNAME}/g" ${PATH_CONF}

    echo_green "创建服务配置文件："
    ${SHELL_CP} ${TEMPLATE_SERVICE} ${PATH_SERVICE}
    ${SHELL_SED} -i "s/\${PORT}/${PORT}/g" ${PATH_SERVICE}

    if [[ "config" == ${ROLE} ]];
    then
        ${SHELL_SED} -i "s/\${CLUSTERROLE}/configsvr/g" ${PATH_CONF}
    elif [[ "shard" == ${ROLE} ]];
    then
        ${SHELL_SED} -i "s/\${CLUSTERROLE}/shardsvr/g" ${PATH_CONF}
    fi

    ${SHELL_CHOWN} mongod.mongod -R ${PATH_DATA_ROOT}

    echo_green "开启服务并查看服务状态："
    ${SHELL_SYSTEMCTL} daemon-reload
    ${SHELL_SERVICE} mongod.${PORT} start
    ${SHELL_SERVICE} mongod.${PORT} status

    echo_green "查看进程信息："
    ${SHELL_PS} -ef | ${SHELL_GREP} mongo | ${SHELL_GREP} -v "ps" | ${SHELL_GREP} -v "^root"
else
    ${SHELL_ECHO} "实例根目录存在，如果需要重新配置，请先卸载服务，然后再进行。"
fi
}

uninstall_service() {
    echo_green "查看服务状态并关闭服务："
    ${SHELL_SYSTEMCTL} daemon-reload
    ${SHELL_SERVICE} mongod.${PORT} status
    ${SHELL_SERVICE} mongod.${PORT} stop

    echo_green "禁用服务并删除服务配置："
    ${SHELL_SYSTEMCTL} disable mongod.${PORT}
    ${SHELL_RM} -rf ${PATH_SERVICE}

    echo_green "删除实例文件夹："
    ${SHELL_RM} -rf ${PATH_DATA_ROOT}
}

case $1 in
    "install") install_service ;;
    "uninstall") uninstall_service ;;
esac
